spring:
  datasource:
    url: jdbc:postgresql://postgres.bookstore-dev.svc.cluster.local:5432/bookstore_dev_db
    username: bookstore_dev_user
    password: bookstore_dev_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

project:
  images: /images/   # <-- make sure this directory exists inside the container

base:
  url: http://10.176.16.161:30083
