name: BookStore Api - Staging

on:
  push:
    branches: [master]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    env:
      GH_VERSION_TAG: staging
      GH_VERSION: staging-${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 1.21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Build .jar file using Maven
        run: mvn clean package -DskipTests

      - name: Check if .jar file exists
        run: |
          ls target/
      - name: Build Docker image
        run: docker build -t mwakazi/bookstore-api:${{ env.GH_VERSION_TAG }} .

      - name: Docker tag
        run: |
          docker tag mwakazi/bookstore-api:${{ env.GH_VERSION_TAG }} mwakazi/bookstore-api:${{ env.GH_VERSION }}

      - name: Push Docker image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_TOKEN }}
        run: |
          echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker push mwakazi/bookstore-api:${{ env.GH_VERSION_TAG }}
          docker push mwakazi/bookstore-api:${{ env.GH_VERSION }}

  # rollout-to-k8s:
  #   runs-on: self-hosted
  #   needs: build-and-push-docker-image
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v4

  #     - name: Setup kubeconfig
  #       run: |
  #         mkdir -p ~/.kube
  #         echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
  #         chmod 600 ~/.kube/config

  #     - name: Set new image on deployment
  #       run: |
  #         kubectl rollout restart deployment/bookstore-api --namespace=bookstore
  #     - name: Rollout status
  #       run: |
  #         kubectl rollout status deployment/bookstore-api --namespace=bookstore